# Makefile for the Linux video drivers.
# 9 May 2019, Eason Chen, <mailto:easonchen@eecgroup.com.tw>
# Rewritten to use lists instead of if-statements.

# Each configuration option enables a list of files.

obj-y                             += am335x-fb.o 
obj-y                             += am335x-mem.o
obj-y                             += RA8875_lcd.o
obj-y                             += RA8875_subroutine.o
